version: "3.8"
services:
    go-app:
        build:
            context: .
            dockerfile: ./docker/go/Dockerfile
        volumes:
            - ./src/go-app:/go/src
        ports:
            - 10881:8080
        working_dir: /go/src
        tty: true
        command: air


    web-server:
        depends_on: 
            - go-app
        build:
            context: .
            dockerfile: ./docker/nginx/Dockerfile
        volumes: 
            - ./docker/nginx/go-app.conf:/etc/nginx/conf.d/go-app.conf
        ports:
            - 10880:81